{{/*
  Shared template fragments for every Spring Boot template, at every version and every kind of
  artefact.

  Inheritance stops repetition BETWEEN files - a level contributes a file once and everything below
  inherits it. These stop repetition INSIDE files: a fragment that belongs in twenty different
  files has nowhere else to live, and copying it means every later change is a find-and-replace
  across the whole tree.

  Collected from every source in the chain, base first, so a deeper level may redefine any of these
  by name. Files matching _*.tpl are never emitted as output.

  Use `include`, not the built-in `template`: the built-in writes straight to the output and cannot
  be piped, so `{{ template "x" . | indent 4 }}` will not parse. `include` returns a string.
*/}}

{{/* Header for generated Java sources. */}}
{{- define "java.header" -}}
/*
 * {{ .ArtifactId }} - {{ .Description }}
 *
 * Generated by scaffold from {{ .Scaffold }} {{ .Version }}. Safe to edit: this file is yours
 * once created, and the generator will not come back and overwrite it.
 */
{{- end }}

{{/* The package declaration plus a blank line, given a sub-package suffix ("" for the root). */}}
{{- define "java.package" -}}
{{- if .suffix -}}
package {{ .root }}.{{ .suffix }};
{{ else -}}
package {{ .root }};
{{ end }}
{{- end }}

{{/* Spring stereotype imports shared by the layered templates. */}}
{{- define "spring.stereotype.imports" -}}
import org.springframework.stereotype.{{ . }};
{{- end }}

{{/*
  The entity's fields, in the three forms Java needs. They come from `data.entity.fields`, declared
  in mvc/jig.yaml and overridable in a values file.

  This is where `data:` and partials pay for each other. The field list is structure, so it has to
  be data; and the same three renderings of it appear in six files across two version lines, so they
  have to be fragments. Written out by hand instead, adding one field to the entity would mean
  editing the model, the DTO, the repository, the service and the controller - twice, once per
  version - and getting every comma right each time.
*/}}

{{/* `String name, int quantity` - a parameter list. */}}
{{- define "entity.params" -}}
{{- range $i, $f := .Data.entity.fields }}{{ if $i }}, {{ end }}{{ $f.type }} {{ $f.name }}{{ end }}
{{- end }}

{{/* `name, quantity` - passing them on. */}}
{{- define "entity.args" -}}
{{- range $i, $f := .Data.entity.fields }}{{ if $i }}, {{ end }}{{ $f.name }}{{ end }}
{{- end }}

{{/* `request.name(), request.quantity()` - unpacking the inbound DTO. */}}
{{- define "entity.requestArgs" -}}
{{- range $i, $f := .Data.entity.fields }}{{ if $i }}, {{ end }}request.{{ $f.name }}(){{ end }}
{{- end }}
