{{/*
  This file contains helper templates for the Spring Boot scaffolding.
  overrides the default helpers in spring-boot/_helpers.tpl, which are shared by all Spring Boot templates.
*/}}


{{- define "java.header" -}}
/*
 * {{ .ArtifactId }} - {{ .Description }}
 *
 * Generated by scaffold from {{ .Scaffold }} {{ .Version }}.
 * Safe to edit: this overrides the default helpers in spring-boot/_helpers.tpl, which are shared by all Spring Boot templates.
 */
{{- end }}
